apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    name: n8n
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: n8n-quota
  namespace: n8n
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
