apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
stringData:
  POSTGRES_USER: n8nuser
  POSTGRES_PASSWORD: n8n-secure-password-2024
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8nuser
  POSTGRES_NON_ROOT_PASSWORD: n8n-secure-password-2024
